### ISSUE TITLE
Download JAI-Images only & location of ground truth / labels

### ISSUE THREAD

**Issue by EyGy** [PRBonn/pybonirob#3]
Hi,
is this Repo still active? I have great interest in (only) obtaining the RGB/NIR images of the JAI camera.
Also is there any kind of ground truth / labeled data available?

Thanks in advance!

**Comment by nivedchebrolu** [comment]
It is possible to get only the JAI images. Check out the [example script ](https://github.com/PRBonn/pybonirob/blob/master/examples/demo_bonirob.py). 
The ground truth labels for a subset of the data can be found here: https://www.ipb.uni-bonn.de/datasets_IJRR2017/annotations/
